### ISSUE TITLE
TIL altitude might be not a number but 'ground' -> crash

### ISSUE THREAD

**Issue by ckrey** [jpmens/1090-to-owntracks#6]
```
{u'squawk': u'2540', u'flight': u'LBT2641 ', u'messages': 117, u'track': 233, u'lon': 6.6821, u'altitude': u'ground', u'hex': u'02a1b0', u'tisb': [], u'nucp': 7, u'mlat': [], u'rssi': -20.4, u'lat': 51.247089, u'seen': 0.5, u'speed': 160, u'seen_pos': 0.9}

Traceback (most recent call last):
  File "./1090-to-owntracks.py", line 46, in <module>
    overhead = get_aircraft()
  File "./1090-to-owntracks.py", line 34, in get_aircraft
    "alt"       : int(craft.get('altitude', 0) / 3.2808),
TypeError: unsupported operand type(s) for /: 'unicode' and 'float'
```

**Comment by vielmetti** [comment]
I patched around this issue with code that looks something like this:

```
       if 'altitude' in craft:
            if craft['altitude'] == 'ground':
                plane['alt']    = 'ground'
            else:
                plane['alt']    = int(float(craft.get('altitude', 0)) / 3.2808)
```

That's not entirely satisfactory because it means that whatever consumes this data will need to deal with an 'alt' value that might be an integer and it might be a string.

**Comment by ckrey** [comment]
correct, I think we need to set

```
plane['alt'] = 0; 
```

in that case
